/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfaceGraphique;

import ControlleurDesAction.ControlleurAdmin;
import ControlleurDesAction.ControlleurDesSaisit;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ya22y
 */
public class InterfaceAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AdminGUI
     */
    public InterfaceAdmin() {
        initComponents();
        input = new InterfaceSaisit(this,false);
        new ControlleurDesSaisit(input,this);
        Qte_input=new InterfaceSaisitQuantité(this,false);
        new ControlleurAdmin(this,Qte_input);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTabel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        SuppButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        ajouterButton = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductTabel.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        ProductTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Nom", "Quantité", "Catégorie", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTabel.setFillsViewportHeight(true);
        ProductTabel.setGridColor(new java.awt.Color(0, 51, 102));
        ProductTabel.setRowHeight(30);
        ProductTabel.setSelectionBackground(new java.awt.Color(255, 51, 51));
        ProductTabel.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ProductTabel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProductTabel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProductTabel.setShowGrid(true);
        ProductTabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ProductTabelFocusGained(evt);
            }
        });
        ProductTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTabel);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1220, 360));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 120));

        searchField.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 51, 102));
        searchField.setText("saisir le nom ou catégorie");
        searchField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        searchField.setSelectionColor(new java.awt.Color(255, 51, 51));
        jPanel2.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 270, 30));

        searchButton.setBackground(new java.awt.Color(0, 51, 102));
        searchButton.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-12-24.png"))); // NOI18N
        searchButton.setText("rechercher");
        searchButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        searchButton.setBorderPainted(false);
        searchButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
        });
        jPanel2.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, 30));

        SuppButton.setBackground(new java.awt.Color(0, 51, 102));
        SuppButton.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        SuppButton.setForeground(new java.awt.Color(255, 255, 255));
        SuppButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/x-mark-4-24.png"))); // NOI18N
        SuppButton.setText("supprimer ");
        SuppButton.setToolTipText("");
        SuppButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        SuppButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SuppButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SuppButtonMouseExited(evt);
            }
        });
        jPanel2.add(SuppButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, -1, -1));

        EditButton.setBackground(new java.awt.Color(0, 51, 102));
        EditButton.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        EditButton.setForeground(new java.awt.Color(255, 255, 255));
        EditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-24.png"))); // NOI18N
        EditButton.setText("modifier ");
        EditButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditButtonMouseExited(evt);
            }
        });
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        jPanel2.add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, -1, -1));

        ajouterButton.setBackground(new java.awt.Color(0, 51, 102));
        ajouterButton.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        ajouterButton.setForeground(new java.awt.Color(255, 255, 255));
        ajouterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus-5-24.png"))); // NOI18N
        ajouterButton.setText("ajouter ");
        ajouterButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        ajouterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajouterButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajouterButtonMouseExited(evt);
            }
        });
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ajouterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 100, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout-48.png"))); // NOI18N
        logout.setBorder(null);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1220, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        
        try {
            this.setVisible(false);
            InterfaceLogin.launch();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(InterfaceAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_logoutActionPerformed

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
                input.setVisible(true);
      
      
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void ProductTabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ProductTabelFocusGained
         row=ProductTabel.getSelectedRow();
        selected=getSelected();
        System.out.println(selected);
    }//GEN-LAST:event_ProductTabelFocusGained

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
       
       if(selected!=null) Qte_input.setVisible(true);
    }//GEN-LAST:event_EditButtonActionPerformed

    private void ProductTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTabelMouseClicked
       row=ProductTabel.getSelectedRow();
        selected=getSelected();
    }//GEN-LAST:event_ProductTabelMouseClicked

    private void ajouterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterButtonMouseEntered
       ajouterButton.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_ajouterButtonMouseEntered

    private void ajouterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterButtonMouseExited
 ajouterButton.setBackground(new Color(00,51,102));    }//GEN-LAST:event_ajouterButtonMouseExited

    private void EditButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseEntered
       if(selected != null){   
        EditButton.setBackground(new Color(0,153,153));
       }else{
           EditButton.setBackground(Color.red);
       }
    }//GEN-LAST:event_EditButtonMouseEntered

    private void EditButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseExited
       EditButton.setBackground(new Color(00,51,102));
    }//GEN-LAST:event_EditButtonMouseExited

    private void SuppButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuppButtonMouseEntered
        if(selected != null){
        SuppButton.setBackground(new Color(0,153,153));
        }else{
            SuppButton.setBackground(Color.red);
        }
    }//GEN-LAST:event_SuppButtonMouseEntered

    private void SuppButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuppButtonMouseExited
       SuppButton.setBackground(new Color(00,51,102));
    }//GEN-LAST:event_SuppButtonMouseExited

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
searchButton.setBackground(new Color(0,153,153));    }//GEN-LAST:event_searchButtonMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
searchButton.setBackground(new Color(0,51,102));    }//GEN-LAST:event_searchButtonMouseExited

    public String getSelected(){
        return ProductTabel.getModel().getValueAt(row, 0).toString();
    }
    
     public void showAllProduct(Object[] rowModel){
        DefaultTableModel model=(DefaultTableModel)ProductTabel.getModel();
               model.addRow(rowModel);
   }
   
     private Integer row=null;
     public String selected=null;
    private InterfaceSaisit input;
    private InterfaceSaisitQuantité Qte_input;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton EditButton;
    public javax.swing.JTable ProductTabel;
    public javax.swing.JButton SuppButton;
    private javax.swing.JButton ajouterButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    public javax.swing.JButton searchButton;
    public javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
