/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package InterfaceGraphique;

/**
 *
 * @author ya22y
 */
public class InterfaceSaisit extends javax.swing.JDialog {

    /**
     * Creates new form DataInputGUI
     */
    public InterfaceSaisit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        nameTextfield = new javax.swing.JTextField();
        qteTextfield = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        description = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        catTextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTextfield.setFont(new java.awt.Font("Waree", 0, 14)); // NOI18N
        nameTextfield.setForeground(new java.awt.Color(0, 51, 102));
        nameTextfield.setText("Nom");
        nameTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom de produit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Waree", 1, 14), new java.awt.Color(0, 51, 102))); // NOI18N
        nameTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextfieldKeyTyped(evt);
            }
        });
        jPanel1.add(nameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, -1));

        qteTextfield.setFont(new java.awt.Font("Waree", 0, 14)); // NOI18N
        qteTextfield.setForeground(new java.awt.Color(0, 51, 102));
        qteTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantité du produit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Waree", 1, 14), new java.awt.Color(0, 51, 102))); // NOI18N
        qteTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qteTextfieldKeyTyped(evt);
            }
        });
        jPanel1.add(qteTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 210, 50));

        addButton.setBackground(new java.awt.Color(0, 51, 102));
        addButton.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Ajouter");
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        description.setFont(new java.awt.Font("Waree", 0, 14)); // NOI18N
        description.setForeground(new java.awt.Color(0, 51, 102));
        description.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Discription", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Waree", 1, 14), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel1.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 510, 80));

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/x-mark-3-32.png"))); // NOI18N
        exitButton.setBorder(null);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        catTextfield.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        catTextfield.setForeground(new java.awt.Color(0, 51, 102));
        catTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catégorie du produit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Waree", 1, 14), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel1.add(catTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/paint(blue).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -90, -1, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextfieldKeyTyped
        checkIfString(evt);
    }//GEN-LAST:event_nameTextfieldKeyTyped

    private void qteTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteTextfieldKeyTyped
        checkIfNumber(evt);
    }//GEN-LAST:event_qteTextfieldKeyTyped

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

   private void checkIfNumber(java.awt.event.KeyEvent evt){
        char c= evt.getKeyChar();
        if(!Character.isDigit(c)|| c==java.awt.event.KeyEvent.VK_BACK_SPACE || c== java.awt.event.KeyEvent.VK_DELETE){
           getToolkit().beep();
           evt.consume();}
    }
    
    private void checkIfString(java.awt.event.KeyEvent evt){
        char c= evt.getKeyChar();
        if(!Character.isAlphabetic(c)|| c==java.awt.event.KeyEvent.VK_BACK_SPACE || c== java.awt.event.KeyEvent.VK_DELETE){
           getToolkit().beep();
           evt.consume();
        }
    }
     
    public String[] getData(){
        return new String[]{nameTextfield.getText(),qteTextfield.getText(),
            catTextfield.getText(),description.getText()};
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addButton;
    private javax.swing.JTextField catTextfield;
    private javax.swing.JTextField description;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JTextField qteTextfield;
    // End of variables declaration//GEN-END:variables
}
